{{- if .Values.enabled }}
{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.secret.name }}
  name: {{ .Values.secret.name }}
  {{- else }}
  name: {{ include "wg-easy.fullname" . }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.environmentVariables }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
