# Default values for wg-easy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: true
replicaCount: 1

image:
  repository: ghcr.io/wg-easy/wg-easy
  pullPolicy: IfNotPresent
  versionOverride: "14"

# This will enable IP forwarding and NAT masquerading
# This is required for the VPN to work in full tunnel mode
command:
  - /bin/sh
  - -c
  - |
    echo "Enabling IP forwarding"
    sysctl -w net.ipv4.ip_forward=1
    iptables -t nat -F POSTROUTING
    iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
    exec node server.js

healthCheckUrl: /
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: 10
environmentVariables:
  # WAN IP or a Dynamic DNS hostname.
  WG_HOST: 85.210.72.64
  WG_DEFAULT_DNS: 1.1.1.1
  # Password for the UI.
  PASSWORD_HASH: '$2a$12$RgkqfzP3XwwFVEw27n90jexsPTwAuj7unmxf0hGOJEQfjnF7LYHNq'

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

secret:
  # Create a secret to store the environment variables. Disabling this
  # and setting a secret name allows users to bring their own secret
  # via the external-secrets-operator or similar. 
  create: false
  # The name of the secret to use.
  # If not set and create is true, a name is generated using the fullname template.
  name:

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true
  allowPrivilegeEscalation: true
  capabilities:
    add:
      - NET_ADMIN
      - SYS_MODULE
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  port: 80
  targetPort: 51821
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/probe-path: "/"
  headless:
    annotations: {}

serviceUdp:
  enabled: true
  port: 51820
  targetPort: 51820

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  hosts:
    - host: wg-stag.fundedtrading.plus
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: wg-easy-tls
  #    hosts:
  #      - wg-easy.local

resources: {}

nodeSelector:

tolerations:
    
affinity: {}

volume:
  enabled: "true"
  className: ""
  annotations:
    helm.sh/resource-policy: "keep"

tests:
  enabled: true
